---
config:
  layout: elk
  look: neo
  
---
classDiagram
direction LR
    class Relatorio {
        -String periodo
        -double totalDespesas
        -double totalReceitas
        +gerarRelatorioCategoria()
        +calcularSaldoAtual()
        +filtrarPorPeriodo()
        +pesquisarPorDescricao()
    }
    class Usuario {
	    -String nome
	    -String email
	    -String senha
	    +cadastrarUsuario()
	    +autenticarUsuario()
    }
    class Transacao {
	    -int id
	    -double valor
	    -Date data
	    -String descricao
	    -String tipo
	    +registrarTransacao()
	    +editarTransacao()
	    +excluirTransacao()
    }
    class Categoria {
        -int id
        -String nome
        -String tipo
        -boolean favorita
        +criarCategoria()
        +listarCategorias()
        +definirFavorita()
        +removerFavorita()
    }
    class Notificacao {
	    -String mensagem
	    -Date dataEnvio
	    +enviarNotificacao()
    }

    

    Usuario "*" --> "1" Transacao : "possui"
    Relatorio "*" --> "1" Transacao : "contém"
    Transacao "*" --> "1" Categoria : "pertence a"
    Usuario "1" --> "1" Notificacao : "recebe"